# Generated by Django 2.1.2 on 2018-10-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='will_want',
            field=models.ManyToManyField(related_name='users_wanting', to='jobs.Job'),
        ),
        migrations.AddField(
            model_name='user',
            name='would_do',
            field=models.ManyToManyField(related_name='users_doing', to='jobs.Job'),
        ),
    ]
