# Generated by Django 2.1.2 on 2018-10-17 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20181017_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='will_want',
            new_name='would_want',
        ),
    ]
